In [1]:
1+1

2

In [1]:
4+4

8

In [2]:
import numpy as np

In [4]:
lst=[1,2,3,4]
arr=np.array(lst)

In [5]:
arr

array([1, 2, 3, 4])

In [6]:
arr.shape

(4,)

In [7]:
type(arr)

numpy.ndarray

In [8]:
arr1=np.array([[1,2,3],[4,5,6]])

In [9]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
arr1.shape    #2 dimensional, 2 rows, 3columns

(2, 3)

In [12]:
arr1.reshape(1,6)    #here 2 open n close brackets so 2 dimensional

array([[1, 2, 3, 4, 5, 6]])

In [13]:
arr1.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
arr1.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [15]:
np.array((1,2,3,4))  #tuple into array

array([1, 2, 3, 4])

In [16]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
arr1.dtype

dtype('int32')

In [20]:
#lets create an array
np.arange(1,20,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [24]:
np.arange(1,20,2).reshape(10,1).shape

(10, 1)

In [26]:
np.array(range(1,20,2))

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [27]:
np.arange(50,1,-2)

array([50, 48, 46, 44, 42, 40, 38, 36, 34, 32, 30, 28, 26, 24, 22, 20, 18,
       16, 14, 12, 10,  8,  6,  4,  2])

In [33]:
np.linspace(1,20,40)  #we get 40 elmts betm 1 to 20

array([ 1.        ,  1.48717949,  1.97435897,  2.46153846,  2.94871795,
        3.43589744,  3.92307692,  4.41025641,  4.8974359 ,  5.38461538,
        5.87179487,  6.35897436,  6.84615385,  7.33333333,  7.82051282,
        8.30769231,  8.79487179,  9.28205128,  9.76923077, 10.25641026,
       10.74358974, 11.23076923, 11.71794872, 12.20512821, 12.69230769,
       13.17948718, 13.66666667, 14.15384615, 14.64102564, 15.12820513,
       15.61538462, 16.1025641 , 16.58974359, 17.07692308, 17.56410256,
       18.05128205, 18.53846154, 19.02564103, 19.51282051, 20.        ])

In [ ]:
#linspace means linearly spaced

In [34]:
np.zeros(4)

array([0., 0., 0., 0.])

In [35]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [36]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [39]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [40]:
np.ones((5,2,8))    #2 rows n 8 cols 5 times, 3dimensional array

array([[[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]]])

In [42]:
5 + np.ones((3,5))

array([[6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.]])

In [43]:
np.eye(4)    #creating identity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [46]:
np.eye(4).reshape(8,2)

array([[1., 0.],
       [0., 0.],
       [0., 1.],
       [0., 0.],
       [0., 0.],
       [1., 0.],
       [0., 0.],
       [0., 1.]])

In [47]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [48]:
print("Random number generation(Uniform distribution)")
np.random.rand(2,3)

Random number generation(Uniform distribution)


array([[0.41599556, 0.65207191, 0.62899134],
       [0.91689125, 0.18035484, 0.90799925]])

In [49]:
print("Random numbers following a Normal distribution with mean=0 and std=1")
print(np.random.randn(5,3))

Random numbers following a Normal distribution with mean=0 and std=1
[[ 1.01753912 -0.35463984  0.65480546]
 [ 0.27643098  0.92631859 -1.86924305]
 [ 0.03062909  0.04566649 -0.59541219]
 [-0.59444199  0.93743866 -1.12517348]
 [-0.69507197 -2.31958476 -0.29375818]]


In [55]:
np.random.randint(1,100,10)  #getting 10 elmts betn 1 to 100

array([68, 11, 48, 18, 70, 97, 31, 81, 70, 64])

In [56]:
np.random.randint(1,100,(4,4))  #4 rows 4 colmns 

array([[66, 16, 49, 89],
       [94, 28,  2, 13],
       [71, 83, 99, 10],
       [49, 50, 50, 21]])

In [58]:
arr=np.arange(0,11)

In [60]:
#slicing
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [62]:
arr[2:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [70]:
arr[2:7]

array([2, 3, 4, 5, 6])

In [71]:
arr[-1:7:-1]

array([10,  9,  8])

In [73]:
arr[-1:3:-1]

array([10,  9,  8,  7,  6,  5,  4])

In [76]:
arr1=np.random.randint(2,100,20).reshape(5,4)

In [77]:
arr1

array([[66, 25, 78, 74],
       [82, 87, 78,  3],
       [22, 52, 54,  2],
       [87, 71, 61, 86],
       [40, 84, 88, 44]])

In [79]:
arr1[0:3]

array([[66, 25, 78, 74],
       [82, 87, 78,  3],
       [22, 52, 54,  2]])

In [80]:
arr1[0:3,0:3]   #seprate for rows n colmns

array([[66, 25, 78],
       [82, 87, 78],
       [22, 52, 54]])

In [85]:
arr1[3:5,1:4]

array([[71, 61, 86],
       [84, 88, 44]])

In [86]:
arr1[2:4,1:3]

array([[52, 54],
       [71, 61]])

In [87]:
arr1[2:4,0:4:3]

array([[22,  2],
       [87, 86]])

In [108]:
#universal functions

arr1=np.random.randint(1,100,(3,3))
arr2=np.random.randint(20,100,(3,3))

In [109]:
arr1

array([[38, 13, 63],
       [ 1, 86,  2],
       [19, 13, 11]])

In [110]:
arr2

array([[96, 94, 41],
       [80, 95, 35],
       [50, 91, 58]])

In [111]:
arr1+arr2     

array([[134, 107, 104],
       [ 81, 181,  37],
       [ 69, 104,  69]])

In [112]:
arr1-arr2

array([[-58, -81,  22],
       [-79,  -9, -33],
       [-31, -78, -47]])

In [121]:
np.matmul(arr1,arr2)

array([[ 7838, 10540,  5667],
       [ 7076,  8446,  3167],
       [ 3414,  4022,  1872]])

In [113]:
arr1/arr2

array([[0.39583333, 0.13829787, 1.53658537],
       [0.0125    , 0.90526316, 0.05714286],
       [0.38      , 0.14285714, 0.18965517]])

In [114]:
np.sqrt(arr1)

array([[6.164414  , 3.60555128, 7.93725393],
       [1.        , 9.2736185 , 1.41421356],
       [4.35889894, 3.60555128, 3.31662479]])

In [115]:
np.sqrt(arr2)

array([[9.79795897, 9.69535971, 6.40312424],
       [8.94427191, 9.74679434, 5.91607978],
       [7.07106781, 9.53939201, 7.61577311]])

In [116]:
np.exp(arr2)

array([[4.92345829e+41, 6.66317622e+40, 6.39843494e+17],
       [5.54062238e+34, 1.81123908e+41, 1.58601345e+15],
       [5.18470553e+21, 3.31740010e+39, 1.54553894e+25]])

In [117]:
np.log10(arr1)

array([[1.5797836 , 1.11394335, 1.79934055],
       [0.        , 1.93449845, 0.30103   ],
       [1.2787536 , 1.11394335, 1.04139269]])

In [118]:
arr1=np.arange(1,10)

In [119]:
arr1[2:]=1000

In [120]:
arr1    #broadcasting